# Esercizio fine modulo M4

In [1]:
import pandas as pd
import numpy as np
dati = pd.read_csv("owid-covid-data.csv", delimiter=",", low_memory=False)

In [2]:
dati.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-03,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-04,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-05,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-06,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-07,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN

## 1) Si richiede di verificare le dimensioni del dataset e le diciture presenti nell'intestazione:

In [23]:
dati.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311365 entries, 0 to 311364
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    311365 non-null  object
 1   continent                                   296585 non-null  object
 2   location                                    311365 non-null  object
 3   date                                        311365 non-null  object
 4   total_cases                                 275335 non-null  float64
 5   new_cases                                   302655 non-null  float64
 6   new_cases_smoothed                          301391 non-null  float64
 7   total_deaths                                254635 non-null  float64
 8   new_deaths                                  302735 non-null  float64
 9   new_deaths_smoothed                         301505 non-null  float64
 10  total_cases_per_million                     275335 non-null  float64
 11  new_cases_per_million                       302655 non-null  float64
 12  new_cases_smoothed_per_million              301391 non-null  float64
 13  total_deaths_per_million                    254635 non-null  float64
 14  new_deaths_per_million                      302735 non-null  float64
 15  new_deaths_smoothed_per_million             301505 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                36050 non-null   float64
 18  icu_patients_per_million                    36050 non-null   float64
 19  hosp_patients                               36840 non-null   float64
 20  hosp_patients_per_million                   36840 non-null   float64
 21  weekly_icu_admissions                       9468 non-null    float64
 22  weekly_icu_admissions_per_million           9468 non-null    float64
 23  weekly_hosp_admissions                      21897 non-null   float64
 24  weekly_hosp_admissions_per_million          21897 non-null   float64
 25  total_tests                                 79387 non-null   float64
 26  new_tests                                   75403 non-null   float64
 27  total_tests_per_thousand                    79387 non-null   float64
 28  new_tests_per_thousand                      75403 non-null   float64
 29  new_tests_smoothed                          103965 non-null  float64
 30  new_tests_smoothed_per_thousand             103965 non-null  float64
 31  positive_rate                               95927 non-null   float64
 32  tests_per_case                              94348 non-null   float64
 33  tests_units                                 106788 non-null  object
 34  total_vaccinations                          74952 non-null   float64
 35  people_vaccinated                           71802 non-null   float64
 36  people_fully_vaccinated                     68318 non-null   float64
 37  total_boosters                              43583 non-null   float64
 38  new_vaccinations                            61685 non-null   float64
 39  new_vaccinations_smoothed                   167733 non-null  float64
 40  total_vaccinations_per_hundred              74952 non-null   float64
 41  people_vaccinated_per_hundred               71802 non-null   float64
 42  people_fully_vaccinated_per_hundred         68318 non-null   float64
 43  total_boosters_per_hundred                  43583 non-null   float64
 44  new_vaccinations_smoothed_per_million       167733 non-null  float64
 45  new_people_vaccinated_smoothed              167798 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  167798 non-null  float64
 47  stringency_index                            197650 non-null  float64
 48  population_density                          264218 non-null  float64
 49  median_age                                  245721 non-null  float64
 50  aged_65_older                               237136 non-null  float64
 51  aged_70_older                               243258 non-null  float64
 52  gdp_per_capita                              240829 non-null  float64
 53  extreme_poverty                             155124 non-null  float64
 54  cardiovasc_death_rate                       241263 non-null  float64
 55  diabetes_prevalence                         253575 non-null  float64
 56  female_smokers                              180977 non-null  float64
 57  male_smokers                                178515 non-null  float64
 58  handwashing_facilities                      118181 non-null  float64
 59  hospital_beds_per_thousand                  212983 non-null  float64
 60  life_expectancy                             286344 non-null  float64
 61  human_development_index                     233879 non-null  float64
 62  population                                  311365 non-null  float64
 63  excess_mortality_cumulative_absolute        10669 non-null   float64
 64  excess_mortality_cumulative                 10669 non-null   float64
 65  excess_mortality                            10669 non-null   float64
 66  excess_mortality_cumulative_per_million     10669 non-null   float64
dtypes: float64(62), object(5)
memory usage: 159.2+ MB

## 2) Si chiede poi per ogni continente di trovare il numero di casi totali avvenuti in quello stesso continente; si chiedi di non considerare eventuali locazioni che nel dataset non appartengono ad alcun continente:

In [50]:
dati.groupby(by = "continent", as_index = False).agg(casi_totali = ("new_cases", np.sum))

       continent  casi_totali
0         Africa   13088991.0
1           Asia  297234406.0
2         Europe  249319188.0
3  North America  124175560.0
4        Oceania   14073975.0
5  South America   68568119.0

## 3) Sempre riguardo i casi di COVID totali, si chiede di sviluppare una funzione che prenda in input il dataset e due nomi di continenti, e che ne confronti i seguenti relativi descrittori statistici: valori minimo e massimo, media, e percentuale rispetto al numero di casi totali nel mondo (in questo caso calcolati anche sulle locazioni senza indicazione di continente):

In [22]:
def funzione1(continent1, continent2):

    dati_continent = dati.loc[:, "continent":"new_cases":4]

    dati_continent1_filtro = dati_continent[dati_continent["continent"]==continent1]
    dati_continent1 = dati_continent1_filtro[dati_continent1_filtro["new_cases"]!=0]
    dati_continent1_cases = dati_continent1.loc[:, "new_cases"]
    dati_continent1_min_cases = dati_continent1_cases.min()
    dati_continent1_max_cases = dati_continent1_cases.max()
    dati_continent1_avg = dati_continent1_cases.mean()

    dati_continent2_filtro = dati_continent[dati_continent["continent"]==continent2]
    dati_continent2 = dati_continent2_filtro[dati_continent2_filtro["new_cases"]!=0]
    dati_continent2_cases = dati_continent2.loc[:, "new_cases"]
    dati_continent2_min_cases = dati_continent2_cases.min()
    dati_continent2_max_cases = dati_continent2_cases.max()
    dati_continent2_avg = dati_continent2_cases.mean()
    
    confronto_continenti = dati.groupby(by = "continent", as_index = False).agg(casi_totali = ("new_cases", np.sum))

    cf_continenti = dati.groupby(by = "continent", as_index = True).agg(casi_totali = ("new_cases", np.sum))

    numeri_confronto = confronto_continenti.loc[:, "casi_totali"].astype(int)
    totale_continent1 = cf_continenti.loc[continent1, :]
    totale_continent2 = cf_continenti.loc[continent2, :]
    totale_casi = numeri_confronto.sum()
    perc_continent1 = (totale_continent1 * 100)/totale_casi
    perc_continent2 = (totale_continent2 * 100)/totale_casi

    differenza_min = dati_continent1_min_cases - dati_continent2_min_cases
    differenza_max = dati_continent1_max_cases - dati_continent2_max_cases
    differenza_avg = dati_continent1_avg - dati_continent2_avg
    differenza_perc = perc_continent1 - perc_continent2

    confronto_dati = {"Min": [dati_continent1_min_cases, dati_continent2_min_cases, differenza_min], "Max": [dati_continent1_max_cases, dati_continent2_max_cases, differenza_max], "Media": [dati_continent1_avg, dati_continent2_avg, differenza_avg], "% su Tot": [perc_continent1, perc_continent2, differenza_perc]}
    confronto = pd.DataFrame(data=confronto_dati, index = [continent1, continent2, "Confronto"])
    print(confronto.round(0).astype(int))

## 4) Si chiede poi di effettuare lo stesso tipo di analisi - anche in questo caso sviluppando una funzione ad hoc - per il numero di vaccinazioni totali per ogni continente:

In [57]:
dati.groupby(by = "continent", as_index = False).agg(vaccinazioni_totali = ("new_vaccinations", np.sum))

       continent  vaccinazioni_totali
0         Africa         1.173671e+08
1           Asia         7.547783e+09
2         Europe         1.264676e+09
3  North America         9.974152e+08
4        Oceania         7.454216e+07
5  South America         8.430426e+08

In [3]:
def funzione2(continent1, continent2):

    dati_continent = dati.loc[:, "continent":"new_vaccinations":37]

    dati_continent1_filtro = dati_continent[dati_continent["continent"]==continent1]
    dati_continent1 = dati_continent1_filtro[dati_continent1_filtro["new_vaccinations"]!=0]
    dati_continent1_vaccinations = dati_continent1.loc[:, "new_vaccinations"]
    dati_continent1_min_vaccinations = dati_continent1_vaccinations.min()
    dati_continent1_max_vaccinations = dati_continent1_vaccinations.max()
    dati_continent1_avg = dati_continent1_vaccinations.mean()

    dati_continent2_filtro = dati_continent[dati_continent["continent"]==continent2]
    dati_continent2 = dati_continent2_filtro[dati_continent2_filtro["new_vaccinations"]!=0]
    dati_continent2_vaccinations = dati_continent2.loc[:, "new_vaccinations"]
    dati_continent2_min_vaccinations = dati_continent2_vaccinations.min()
    dati_continent2_max_vaccinations = dati_continent2_vaccinations.max()
    dati_continent2_avg = dati_continent2_vaccinations.mean()

    confronto_continente = dati.groupby(by = "continent", as_index = False).agg(vaccinations_totali = ("new_vaccinations", np.sum))

    cf_continenti = dati.groupby(by = "continent", as_index = True).agg(vaccinations_totali = ("new_vaccinations", np.sum))

    numeri_confronto = confronto_continente.loc[:, "vaccinations_totali"]
    totale_continent1 = cf_continenti.loc[continent1, "vaccinations_totali"]
    totale_continent2 = cf_continenti.loc[continent2, "vaccinations_totali"]
    totale_vaccinations = numeri_confronto.sum()
    perc_continent1 = (totale_continent1 * 100)/totale_vaccinations
    perc_continent2 = (totale_continent2 * 100)/totale_vaccinations

    differenza_min = dati_continent1_min_vaccinations - dati_continent2_min_vaccinations
    differenza_max = dati_continent1_max_vaccinations - dati_continent2_max_vaccinations
    differenza_avg = dati_continent1_avg - dati_continent2_avg
    differenza_perc = perc_continent1 - perc_continent2

    confronto_dati = {"Min": [dati_continent1_min_vaccinations, dati_continent2_min_vaccinations, differenza_min], "Max": [dati_continent1_max_vaccinations, dati_continent2_max_vaccinations, differenza_max], "Media": [dati_continent1_avg, dati_continent2_avg, differenza_avg], "% su Tot": [perc_continent1, perc_continent2, differenza_perc]}
    confronto = pd.DataFrame(data=confronto_dati, index = [continent1, continent2, "Confronto"])
    print(confronto.round(0).astype(int))

## 5) Alla fine, basandosi sui calcoli fatti, il committente chiede di stilare un breve (tre o quattro righe) paragrafo testuale riassuntivo sulle statistiche di casi e vaccinazioni, che si concentri solo sulle differenze esistenti tra Europa, Sud America e Oceania:

In [20]:
def confronto_casi_covid(continent1, continent2, continent3):
    
    dati_continent = dati.loc[:, "continent":"new_cases":4]

    dati_continent1_filtro = dati_continent[dati_continent["continent"]==continent1]
    dati_continent1 = dati_continent1_filtro[dati_continent1_filtro["new_cases"]!=0]
    dati_continent1_cases = dati_continent1.loc[:, "new_cases"]
    dati_continent1_min_cases = dati_continent1_cases.min()
    dati_continent1_max_cases = dati_continent1_cases.max()
    dati_continent1_avg = dati_continent1_cases.mean()

    dati_continent2_filtro = dati_continent[dati_continent["continent"]==continent2]
    dati_continent2 = dati_continent2_filtro[dati_continent2_filtro["new_cases"]!=0]
    dati_continent2_cases = dati_continent2.loc[:, "new_cases"]
    dati_continent2_min_cases = dati_continent2_cases.min()
    dati_continent2_max_cases = dati_continent2_cases.max()
    dati_continent2_avg = dati_continent2_cases.mean()
    
    dati_continent3_filtro = dati_continent[dati_continent["continent"]==continent3]
    dati_continent3 = dati_continent3_filtro[dati_continent3_filtro["new_cases"]!=0]
    dati_continent3_cases = dati_continent3.loc[:, "new_cases"]
    dati_continent3_min_cases = dati_continent3_cases.min()
    dati_continent3_max_cases = dati_continent3_cases.max()
    dati_continent3_avg = dati_continent3_cases.mean()
    
    confronto_continenti = dati.groupby(by = "continent", as_index = False).agg(casi_totali = ("new_cases", np.sum))

    cf_continenti = dati.groupby(by = "continent", as_index = True).agg(casi_totali = ("new_cases", np.sum))

    numeri_confronto = confronto_continenti.loc[:, "casi_totali"].astype(int)
    totale_continent1 = cf_continenti.loc[continent1, :]
    totale_continent2 = cf_continenti.loc[continent2, :]
    totale_continent3 = cf_continenti.loc[continent3, :]
    totale_casi = numeri_confronto.sum()
    perc_continent1 = (totale_continent1 * 100)/totale_casi
    perc_continent2 = (totale_continent2 * 100)/totale_casi
    perc_continent3 = (totale_continent3 * 100)/totale_casi    

    confronto_dati = {"Min": [dati_continent1_min_cases, dati_continent2_min_cases, dati_continent3_min_cases], "Max": [dati_continent1_max_cases, dati_continent2_max_cases, dati_continent3_max_cases], "Media": [dati_continent1_avg, dati_continent2_avg, dati_continent3_avg], "% su Tot": [perc_continent1, perc_continent2, perc_continent3]}
    confronto = pd.DataFrame(data=confronto_dati, index = [continent1, continent2, continent3])
    print(confronto.round(0).astype(int))

In [21]:
def confronto_vaccinazioni(continent1, continent2, continent3):

    dati_continent = dati.loc[:, "continent":"new_vaccinations":37]

    dati_continent1_filtro = dati_continent[dati_continent["continent"]==continent1]
    dati_continent1 = dati_continent1_filtro[dati_continent1_filtro["new_vaccinations"]!=0]
    dati_continent1_vaccinations = dati_continent1.loc[:, "new_vaccinations"]
    dati_continent1_min_vaccinations = dati_continent1_vaccinations.min()
    dati_continent1_max_vaccinations = dati_continent1_vaccinations.max()
    dati_continent1_avg = dati_continent1_vaccinations.mean()

    dati_continent2_filtro = dati_continent[dati_continent["continent"]==continent2]
    dati_continent2 = dati_continent2_filtro[dati_continent2_filtro["new_vaccinations"]!=0]
    dati_continent2_vaccinations = dati_continent2.loc[:, "new_vaccinations"]
    dati_continent2_min_vaccinations = dati_continent2_vaccinations.min()
    dati_continent2_max_vaccinations = dati_continent2_vaccinations.max()
    dati_continent2_avg = dati_continent2_vaccinations.mean()
    
    dati_continent3_filtro = dati_continent[dati_continent["continent"]==continent3]
    dati_continent3 = dati_continent3_filtro[dati_continent3_filtro["new_vaccinations"]!=0]
    dati_continent3_vaccinations = dati_continent3.loc[:, "new_vaccinations"]
    dati_continent3_min_vaccinations = dati_continent3_vaccinations.min()
    dati_continent3_max_vaccinations = dati_continent3_vaccinations.max()
    dati_continent3_avg = dati_continent3_vaccinations.mean()

    confronto_continente = dati.groupby(by = "continent", as_index = False).agg(vaccinations_totali = ("new_vaccinations", np.sum))

    cf_continenti = dati.groupby(by = "continent", as_index = True).agg(vaccinations_totali = ("new_vaccinations", np.sum))

    numeri_confronto = confronto_continente.loc[:, "vaccinations_totali"]
    totale_continent1 = cf_continenti.loc[continent1, "vaccinations_totali"]
    totale_continent2 = cf_continenti.loc[continent2, "vaccinations_totali"]
    totale_continent3 = cf_continenti.loc[continent3, "vaccinations_totali"]
    totale_vaccinations = numeri_confronto.sum()
    perc_continent1 = (totale_continent1 * 100)/totale_vaccinations
    perc_continent2 = (totale_continent2 * 100)/totale_vaccinations
    perc_continent3 = (totale_continent2 * 100)/totale_vaccinations

    confronto_dati = {"Min": [dati_continent1_min_vaccinations, dati_continent2_min_vaccinations, dati_continent3_min_vaccinations], "Max": [dati_continent1_max_vaccinations, dati_continent2_max_vaccinations, dati_continent3_max_vaccinations], "Media": [dati_continent1_avg, dati_continent2_avg, dati_continent3_avg], "% su Tot": [perc_continent1, perc_continent2, perc_continent3]}
    confronto = pd.DataFrame(data=confronto_dati, index = [continent1, continent2, continent3])
    print(confronto.round(0).astype(int))

### Tabella 1 - Confronto casi di covid

In [23]:
confronto_casi_covid("Europe", "South America", "Oceania")

               Min     Max  Media  % su Tot
Europe           1  500563   4978        32
South America    1  298408   5731         8
Oceania          1  588813   2562         1

### Tabella 2 - Confronto vaccinazioni

In [8]:
confronto_vaccinazioni("Europe", "South America", "Oceania")

               Min      Max   Media  % su Tot
Europe           1  2389472   60260        12
South America    1  3976605  150921         8
Oceania          1   351226   56859         8

#### Dalle due tabelle sovrastanti, che racchiudono alcune statistiche riguardanti i casi covid (Tabella 1) e il numero di vaccinazioni (Tabella 2) dei continenti indicati, possiamo notare che:

- L'Oceania Ã¨ il continente che ha raggiunto il numero piÃ¹ alto di casi giornalieri con 588.813 casi;
- Il numero minimo di casi giornalieri pari a 1 probabilmente Ã¨ dovuto ai primi giorni dalla scoperta del virus, quando venivano registrati i primi pazienti 0;
- La media di casi giornalieri per il Sud America Ã¨ la piÃ¹ alta tra quelli presi in esame con 5731 casi giornalieri, mentre l'Oceania la media piÃ¹ bassa, 2562;
- L'Europa detiene invece il numero piÃ¹ alti di casi rispetto al totale mondiale, il 32%;

- Per quanto riguarda le vaccinazioni, l'Europa Ã¨ il paese con un piÃ¹ alto numero di vaccinati rispetto agli altri due paesi (12%);
- Sempre parlando di vaccinazioni, il Sud America Ã¨ quello che ha effettuato piÃ¹ vaccinazioni in una giornata (351.226) e ha la media giornaliera piÃ¹ alta (150.951), quasi il triplo rispetto agli altri due continenti presi in esame.